from . import native_adaptation

GIT_CHECKOUT_OPTIONS_VERSION = 1
GIT_DIFF_OPTIONS_VERSION = 1
GIT_REPOSITORY_INIT_OPTIONS_VERSION = 1
GIT_STATUS_OPTIONS_VERSION = 1

GIT_OID_RAWSZ = GIT_OID_SHA1_SIZE = 20
GIT_OID_HEXSZ = GIT_OID_SHA1_HEXSIZE = GIT_OID_SHA1_SIZE * 2

GIT_STATUS_OPT_DEFAULTS = (
    native_adaptation.git_status_opt_t.INCLUDE_IGNORED
    | native_adaptation.git_status_opt_t.INCLUDE_UNTRACKED
    | native_adaptation.git_status_opt_t.RECURSE_UNTRACKED_DIRS
)
