---
# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  ci-smoketests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: Install absolufy and uv
        run: |
          python3 -m pip install absolufy-imports uv

      - name: Enforce relative imports in package
        run: >
          find rpmautospec -name \*.py -print0
          | xargs -0 absolufy-imports --never

      - name: Check uv lock file consistency
        run: >
          uv lock --check

  ci-testsuite:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toxenv: py39
            fedver: f38
          - toxenv: py39-all-extras
            fedver: f38
          - toxenv: py310
            fedver: f38
          - toxenv: py310-all-extras
            fedver: f38
          - toxenv: py311
            fedver: f38
          - toxenv: py311-all-extras
            fedver: f38
          - toxenv: py312
            fedver: latest
          - toxenv: py312-all-extras
            fedver: latest
          - toxenv: py313
            fedver: latest
          - toxenv: py313-all-extras
            fedver: latest
          - toxenv: py314
            fedver: latest
          - toxenv: py314-all-extras
            fedver: latest
            extrapkgs: libgit2-devel
    runs-on: ubuntu-latest
    container: "fedorapython/fedora-python-tox:${{ matrix.fedver }}"
    steps:
      - uses: actions/checkout@v5

      - name: Mark the directory as safe for git
        run: git config --global --add safe.directory $PWD

      - name: Configure git user
        run: |
          git config --global user.name "Git User"
          git config --global user.email "git-user@example.com"

      - name: Install basic RPM dependencies
        run: >
          dnf -y install
          gcc
          glibc-langpack-de
          glibc-langpack-en
          hatch
          krb5-devel
          libffi-devel
          libgit2
          python3-rpm
          rpm
          rpm-build
          ${{ matrix.extrapkgs }}

      - name: run tests through tox
        run: "tox -e ${{ matrix.toxenv }}"

  ci-statictests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: run tests through tox
        run: "tox -e format,lint"
